name: River Valley Paddle Co.
favicon: null
layout_spectrum: 0.04250845848582685
typography_spectrum: 0.34456856292672455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4053351415786892
  lightness: 0.27533004130236804
  saturation: 0.30402860790491104
  rhythmicContrast: 0.48628228274174035
purpose: []
